# Generated by Django 4.2.7 on 2025-08-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("PARENT", "Parent Company"),
                    ("SUBSIDIARY", "Subsidiary"),
                    ("DIVISION", "Division"),
                ],
                default="PARENT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="parent_company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subsidiaries",
                to="companies.company",
            ),
        ),
        migrations.CreateModel(
            name="Entity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("entity_code", models.CharField(max_length=20)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("DIVISION", "Division"),
                            ("SUBSIDIARY", "Subsidiary"),
                            ("DEPARTMENT", "Department"),
                            ("PROJECT", "Project"),
                            ("REGION", "Regional Office"),
                        ],
                        default="DIVISION",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField(blank=True)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entities",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Entities",
                "db_table": "entities",
                "unique_together": {("company", "entity_code")},
            },
        ),
    ]
