# Generated by Django 4.2.7 on 2025-08-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_company_type_company_parent_company_entity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entity",
            name="entity_type",
            field=models.CharField(default="DIVISION", max_length=50),
        ),
    ]
