# Generated by Django 4.2.7 on 2025-07-31 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("designation", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                (
                    "employee_type",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("SAFETY_OFFICER", "Safety Officer"),
                            ("PLANT_MANAGER", "Plant Manager"),
                            ("SUPERVISOR", "Supervisor"),
                            ("OPERATOR", "Operator"),
                            ("MAINTENANCE", "Maintenance Staff"),
                            ("CONTRACTOR", "Contractor"),
                        ],
                        default="OPERATOR",
                        max_length=20,
                    ),
                ),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("can_access_admin", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "primary_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sites.site",
                    ),
                ),
                (
                    "sites",
                    models.ManyToManyField(
                        blank=True, related_name="employees", to="sites.site"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "employees",
            },
        ),
    ]
