# Generated by Django 4.2.7 on 2025-08-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_company_type_company_parent_company_entity"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="entities",
            field=models.ManyToManyField(
                blank=True, related_name="employees", to="companies.entity"
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="primary_entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="companies.entity",
            ),
        ),
    ]
