# Generated by Django 4.2.7 on 2025-08-01 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_alter_site_options_and_more"),
        ("companies", "0003_alter_entity_entity_type"),
        ("employees", "0002_employee_entities_employee_primary_entity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["name"]},
        ),
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="employee_type",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="entities",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="primary_entity",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="primary_site",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="sites",
        ),
        migrations.CreateModel(
            name="EmployeeAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        help_text="Job title/position (e.g., Senior Engineer, Project Manager)",
                        max_length=100,
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        help_text="Department name (e.g., Operations, Maintenance, Safety)",
                        max_length=100,
                    ),
                ),
                (
                    "employee_type",
                    models.CharField(
                        help_text="Employee category (e.g., Full-time, Contractor, Consultant)",
                        max_length=50,
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary assignment for this employee"
                    ),
                ),
                ("start_date", models.DateField(help_text="Assignment start date")),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Assignment end date (leave blank if ongoing)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this assignment is currently active",
                    ),
                ),
                (
                    "salary_grade",
                    models.CharField(
                        blank=True, help_text="Salary grade or level", max_length=20
                    ),
                ),
                (
                    "work_location",
                    models.CharField(
                        blank=True, help_text="Specific work location", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="employees.employee",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_assignments",
                        to="companies.entity",
                    ),
                ),
                (
                    "reporting_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="employees.employeeassignment",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_assignments",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "db_table": "employee_assignments",
                "ordering": ["-is_primary", "-start_date"],
                "unique_together": {("employee", "entity", "site", "designation")},
            },
        ),
    ]
