# Generated by Django 4.2.7 on 2025-08-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0003_alter_employee_options_remove_employee_department_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employeeassignment",
            name="employee_type",
        ),
    ]
