# Generated by Django 4.2.7 on 2025-08-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_remove_employeeassignment_employee_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="show_in_emergency_contacts",
            field=models.BooleanField(
                default=False,
                help_text="Show this employee in public emergency contacts",
            ),
        ),
    ]
