# Generated by Django 4.2.7 on 2025-08-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employee_show_in_emergency_contacts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="show_in_emergency_contacts",
        ),
        migrations.AddField(
            model_name="employeeassignment",
            name="show_in_emergency_contacts",
            field=models.BooleanField(
                default=False,
                help_text="Show this employee as emergency contact for this assignment",
            ),
        ),
    ]
