# Generated by Django 4.2.7 on 2025-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_remove_employee_show_in_emergency_contacts_and_more"),
    ]

    operations = [
        # Add new fields to Employee model
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, help_text='Job title/position', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, help_text='Department name', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='location_type',
            field=models.CharField(choices=[('site', 'Site'), ('entity', 'Entity'), ('headquarters', 'Headquarters'), ('company', 'Company')], default='site', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='location_id',
            field=models.CharField(default='1', help_text='ID of the specific location (site ID, entity ID, or \'headquarters\'/\'company\')', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='show_in_emergency_contacts',
            field=models.BooleanField(default=False, help_text='Show this employee as emergency contact'),
        ),
        
        # Remove old fields
        migrations.RemoveField(
            model_name='employee',
            name='date_of_joining',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='can_access_admin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        
        # Drop the EmployeeAssignment table
        migrations.DeleteModel(
            name='EmployeeAssignment',
        ),
    ]
