# Generated by Django 4.2.7 on 2025-08-03 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_auto_20250803_1459"),
    ]

    operations = [
        # Create the new EmployeeLocation model
        migrations.CreateModel(
            name='EmployeeLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(choices=[('site', 'Site'), ('entity', 'Entity'), ('headquarters', 'Headquarters'), ('company', 'Company')], max_length=20)),
                ('location_id', models.CharField(help_text='ID of the specific location', max_length=50)),
                ('show_in_emergency_contacts', models.BooleanField(default=False, help_text='Show this employee as emergency contact for this location')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this location assignment is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='employees.employee')),
            ],
            options={
                'db_table': 'employee_locations',
                'ordering': ['location_type', 'location_id'],
            },
        ),
        
        # Add unique constraint
        migrations.AlterUniqueTogether(
            name='employeelocation',
            unique_together={('employee', 'location_type', 'location_id')},
        ),
        
        # Remove old fields from Employee model
        migrations.RemoveField(
            model_name='employee',
            name='location_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='show_in_emergency_contacts',
        ),
    ]
