# Generated by Django 4.2.7 on 2025-07-31 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=100, unique=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("MOBILE", "Mobile Device"),
                            ("TABLET", "Tablet"),
                            ("KIOSK", "Reporting Kiosk"),
                        ],
                        default="MOBILE",
                        max_length=20,
                    ),
                ),
                ("last_active", models.DateTimeField(auto_now=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("location_enabled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "db_table": "device_status",
            },
        ),
    ]
