# Generated by Django 4.2.7 on 2025-08-11 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=100)),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("SITE_MANAGER", "Site Manager"),
                            ("SAFETY_OFFICER", "Safety Officer"),
                            ("EMERGENCY_RESPONSE", "Emergency Response"),
                            ("GENERAL", "General Contact"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                ("is_available_24_7", models.BooleanField(default=False)),
                ("availability_notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="companies.company",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
                "ordering": ["-is_primary", "name"],
            },
        ),
    ]
