# Generated by Django 4.2.7 on 2025-08-11 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("site_code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "plant_type",
                    models.CharField(
                        choices=[
                            ("SOLAR", "Solar Power Plant"),
                            ("WIND", "Wind Power Plant"),
                            ("HYDRO", "Hydro Power Plant"),
                            ("THERMAL", "Thermal Power Plant"),
                            ("OTHER", "Other"),
                        ],
                        default="SOLAR",
                        max_length=20,
                    ),
                ),
                ("capacity", models.CharField(blank=True, max_length=50)),
                (
                    "operational_status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("SHUTDOWN", "Shutdown"),
                            ("PLANNING", "Planning Phase"),
                        ],
                        default="OPERATIONAL",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled_forms", models.JSONField(blank=True, default=list)),
                ("show_phone", models.BooleanField(default=True)),
                ("show_email", models.BooleanField(default=True)),
                ("show_address", models.BooleanField(default=True)),
                ("quick_info_config", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="siteconfiguration",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configurations",
            },
        ),
    ]
