# Generated by Django 4.2.7 on 2025-07-31 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("site_code", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(default="India", max_length=100)),
                ("country_code", models.CharField(default="IND", max_length=5)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Latitude coordinate (-90 to 90)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7,
                        help_text="Longitude coordinate (-180 to 180)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "plant_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SOLAR", "Solar Power Plant"),
                            ("WIND", "Wind Power Plant"),
                            ("THERMAL", "Thermal Power Plant"),
                            ("HYDRO", "Hydro Power Plant"),
                            ("NUCLEAR", "Nuclear Power Plant"),
                            ("BIOMASS", "Biomass Power Plant"),
                            ("GEOTHERMAL", "Geothermal Power Plant"),
                            ("HYBRID", "Hybrid Power Plant"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        blank=True,
                        help_text="Plant capacity (e.g., 100 MW, 50 MWp)",
                        max_length=100,
                    ),
                ),
                (
                    "operational_status",
                    models.CharField(
                        choices=[
                            ("OPERATIONAL", "Operational"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("SHUTDOWN", "Shutdown"),
                            ("COMMISSIONING", "Under Commissioning"),
                            ("DECOMMISSIONED", "Decommissioned"),
                        ],
                        default="OPERATIONAL",
                        max_length=20,
                    ),
                ),
                ("commissioned_date", models.DateField(blank=True, null=True)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sites",
                        to="companies.company",
                    ),
                ),
            ],
            options={
                "db_table": "sites",
                "ordering": ["company", "name"],
                "indexes": [
                    models.Index(
                        fields=["company", "is_active"], name="sites_company_7df74e_idx"
                    ),
                    models.Index(fields=["site_code"], name="sites_site_co_a1890d_idx"),
                    models.Index(
                        fields=["operational_status"], name="sites_operati_56ee0b_idx"
                    ),
                ],
                "unique_together": {("company", "site_code")},
            },
        ),
    ]
