# Generated by Django 4.2.7 on 2025-08-01 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="enabled_forms",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of enabled form types for this site",
            ),
        ),
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_config",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Configuration for individual forms",
                    ),
                ),
                ("show_safety_officer", models.BooleanField(default=True)),
                ("show_emergency_contacts", models.BooleanField(default=True)),
                ("show_quick_info", models.BooleanField(default=True)),
                ("custom_title", models.CharField(blank=True, max_length=200)),
                ("custom_description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "db_table": "site_configurations",
            },
        ),
    ]
