# Generated by Django 4.2.7 on 2025-08-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0002_site_enabled_forms_siteconfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="quick_info_config",
            field=models.JSONField(
                blank=True, default=dict, help_text="Configuration for Quick Info cards"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="show_emergency_contacts",
            field=models.BooleanField(
                default=True, help_text="Show Emergency Contacts section"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="show_quick_info",
            field=models.BooleanField(
                default=True, help_text="Show Quick Info section"
            ),
        ),
        migrations.AlterField(
            model_name="siteconfiguration",
            name="show_safety_officer",
            field=models.BooleanField(
                default=True, help_text="Show Safety Officer section"
            ),
        ),
    ]
