# Generated by Django 4.2.7 on 2025-08-01 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0002_company_company_type_company_parent_company_entity"),
        ("sites", "0003_siteconfiguration_quick_info_config_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="site",
            options={"ordering": ["entity", "name"]},
        ),
        migrations.RemoveIndex(
            model_name="site",
            name="sites_company_7df74e_idx",
        ),
        migrations.AlterUniqueTogether(
            name="site",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="site",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="companies.entity",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="site",
            unique_together={("entity", "site_code")},
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(
                fields=["entity", "is_active"], name="sites_entity__7fac3f_idx"
            ),
        ),
        migrations.RemoveField(
            model_name="site",
            name="company",
        ),
    ]
