# Generated by Django 4.2.7 on 2025-07-31 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NationalEmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("FIRE_DEPARTMENT", "Fire Department"),
                            ("POLICE", "Police"),
                            ("MEDICAL_EMERGENCY", "Medical Emergency"),
                            ("DISASTER_MANAGEMENT", "Disaster Management"),
                            ("POLLUTION_CONTROL", "Pollution Control Board"),
                            ("ELECTRICITY_BOARD", "Electricity Board"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("is_national", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("priority_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "national_emergency_contacts",
                "ordering": ["priority_order", "contact_type"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contact_type",
                    models.CharField(
                        choices=[
                            ("SAFETY_INCHARGE", "Safety Incharge"),
                            ("PLANT_INCHARGE", "Plant Incharge"),
                            ("ADMIN", "Admin"),
                            ("PLANT_MANAGER", "Plant Manager"),
                            ("SAFETY_OFFICER", "Safety Officer"),
                            ("ELECTRICAL_ENGINEER", "Electrical Engineer"),
                            ("MAINTENANCE_SUPERVISOR", "Maintenance Supervisor"),
                            ("FIRE_DEPARTMENT", "Fire Department"),
                            ("MEDICAL_EMERGENCY", "Medical Emergency"),
                            ("UTILITY_GRID", "Utility Grid Control"),
                            ("SECURITY", "Plant Security"),
                            ("ENVIRONMENTAL_OFFICER", "Environmental Officer"),
                            ("CORPORATE_HQ", "Corporate Headquarters"),
                        ],
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("designation", models.CharField(max_length=100)),
                ("primary_phone", models.CharField(max_length=20)),
                ("secondary_phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("is_24x7_available", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("priority_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="sites.site",
                    ),
                ),
            ],
            options={
                "db_table": "emergency_contacts",
                "ordering": ["priority_order", "contact_type"],
                "unique_together": {("site", "contact_type", "name")},
            },
        ),
    ]
