# Generated by Django 4.2.7 on 2025-08-01 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0004_alter_site_options_and_more"),
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incidents",
                to="sites.site",
            ),
        ),
    ]
